# Reference:
# - https://doc.rust-lang.org/stable/clippy/continuous_integration/github_actions.html
# - https://github.com/actions/starter-workflows/blob/main/ci/rust.yml
on: push

name: Build and Test

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install gpio-sim
        run: |
          sudo apt-get update
          sudo apt-get install linux-modules-extra-$(uname -r)
          sudo modprobe gpio-sim
      - name: Build
        run: cargo build --verbose
      - name: Run fmt
        run: cargo fmt
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER='sudo -E' cargo test --verbose
